services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  keycloack:
    image: quay.io/keycloak/keycloak:18.0.0
    environment:
      KEYCLOAK_ADMIN: keycloack
      KEYCLOAK_ADMIN_PASSWORD: keycloack
    ports:
      - 8081:8080
    command:
      - start-dev
