spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgres
  jpa:
    show-sql: false
  mvc:
    format:
      date: iso
      date-time: iso
      time: iso
